baseURL = "https://jennyKuopd.github.io/"
languageCode = "zh-tw"
title = "Jenny｜Product designer"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Jenny Kuo , Product Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.jpg"
    logo = "logo.png"
    email = "dias3839@gmail.com"
    dribbble = "https://dribbble.com/jennykuo/about"
    linkedin = "https://www.linkedin.com/in/yen-chun-kuo-748412113/"
    medium = "https://medium.com/@dias3839"
    behance = "https://www.behance.net/Jennykuo0523"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "Jennyphoto.jpeg"
    subtitle = "Hi! I'm Jenny, a UX/UI Designer and from Taiwan."
    hero_right = ["**您好，我是Jenny，目前在振曜科技擔任UX/UI Designer，畢業於國立雲林科技大學工業設計所，以服務設計去思考產品希望能夠找出更好的使用者洞察，擅長研究與UX來找出最佳策略，並運用UI與視覺的能力為產品帶來更良好的體驗。**", "Hello, my name is Jenny. I am currently working as a UX/UI Designer at Netronix Inc. I graduated from the Industrial Design Institute of National Yunlin University of Science and Technology. I use service design to think about products, hoping to find better user insights. I am good at research and UX. Find the best strategy and use the power of UI and visual to bring a better experience to the product."]
    resume = "JennyResume.pdf"

[params.process]
    enable = true
    title = "Process Design"
    subtitle = "Design skill"

[params.case_studies]
    enable = true
    title = "UI/UX"
    subtitle = "Find the best solution through discussion and cooperation."

[params.case_studies_item]
    enable = true
    title = "A design"
    subtitle = "Selected Works"


[params.case_uiux]
    enable = true
    title = "UIUX"
    subtitle = "User interface & Experience"

    

[params.footer]
    enable = true
